using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sitecore.PlaceholderRules
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{1D38B82B-6CFD-4F8F-8745-5364DA58107E}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Placeholder Settings/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Placeholder_Settings = new ID("{1D38B82B-6CFD-4F8F-8745-5364DA58107E}");
    }
}
